name: docker
on:
  workflow_dispatch: # manually run
    inputs:
      target:
        description: 'Target to publish'
        required: true
      tag:
        description: 'Tag'
        required: true

env:
  CI: true

jobs:
  publish:
    name: docker-publish
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: eldar
          password: ${{ secrets.EG_DOCKER_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: "docker build . --target $TARGET -t eldar/$TARGET:$TAG"
        env:
          TARGET: ${{ github.event.inputs.target }}
          TAG: ${{ github.event.inputs.tag }}

      - name: Publish
        run: "docker push eldar/$TARGET:$TAG"
        env:
          TARGET: ${{ github.event.inputs.target }}
          TAG: ${{ github.event.inputs.tag }}
